### ISSUE TITLE
enabling/disabling certain events in config file

### ISSUE THREAD

**Issue by nekoizumi** [BudgetAirpods/InsanityRemastered#2]
i could see my friends loving more auditory hallucinations and fake players. but they also might not like fake items or eventually having their models swap with monsters. being able to pick and choose what can happen as a modpack curator would be very helpful.

**Comment by Clark919** [comment]
Agreed with this. This is a cool concept but it's in dire need of config options to specify what is enabled.

**Comment by BudgetAirpods** [comment]
Thank you all for the suggestions. This has been added into the recent update. Will make more things tweakable in future updates.
