### ISSUE TITLE
Slow walk +Run after regen insanity.

### ISSUE THREAD

**Issue by LoveCupidxo** [BudgetAirpods/InsanityRemastered#3]
Hey, I was excited to finally find an insanity mod and quickly downloaded this mod after being released. However, I ran into a bug that happens once your person experiences a panic attack and you leave the building to calm down, you lose any speed from both walking + running. I'm not sure if it's programmed like that one purpose, but even when I switched to company and march my player was still very low in stamina despite being mentally sound (in-game.)

It left me pretty much useless to my other teammates, to which I had no choice but to stay back on the ship LOL!! XP

**Comment by BudgetAirpods** [comment]
Hello. I am in the process of fixing this. It will be in the next update which (if I have time) should. E tomorrow. Don't wanna make any promises though
