### ISSUE TITLE
[Error  :BudgetAirpods.InsanityRemastered] Failed to load audio assets!

### ISSUE THREAD

**Issue by Senjay-id** [BudgetAirpods/InsanityRemastered#34]
[Info   :   BepInEx] Loading [Insanity Remastered 1.1.1]
[Error  :BudgetAirpods.InsanityRemastered] Failed to load audio assets!
[Info   :   BepInEx] Loading [ShipLobby 1.0.2]
[Info   :   BepInEx] Loading [Custom Boombox Music 1.4.0]

Is the error log intended ?

installed through r2modman

**Comment by BudgetAirpods** [comment]
This is unintentional. I changed the file hierarchy for the mod in the recent update, which seems to make the mod managers unhappy.

**Comment by MiyamiEthan** [comment]
> [Info : BepInEx] Loading [Insanity Remastered 1.1.1] [Error :BudgetAirpods.InsanityRemastered] Failed to load audio assets! [Info : BepInEx] Loading [ShipLobby 1.0.2] [Info : BepInEx] Loading [Custom Boombox Music 1.4.0]
> 
> Is the error log intended ?
> 
> installed through r2modman

I downgraded to 1.0.8 and this issue resolved, but this is obviously a temp fix

**Comment by Justuuz** [comment]
i fix it for me somehow

instead of
"C:\Users\User\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Test\BepInEx\plugins\BudgetAirpods-InsanityRemastered"

I change it to
"C:\Users\User\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Mod\BepInEx\plugins\InsanityRemastered"

i think the error cause was the wrong folder name.
Instead of "BudgetAirpods-InsanityRemastered" i change it to "InsanityRemastered"

Now its totally fine

**Comment by Senjay-id** [comment]
so yeah it can be fixed by changing this line of code at InsanityRemasteredContent.cs
`private static string DataFolder => Path.GetFullPath(Paths.PluginPath + "/InsanityRemastered");`
to
`private static string DataFolder => Path.GetFullPath(Paths.PluginPath + "/BudgetAirpods-InsanityRemastered");`

**Comment by Aleph-Zero0** [comment]
You should know, that r2modman adds mod creator's name before the mod name when creating config files/folders for it, so the actual path must be "C:\Users\\"username"\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\\"profilename"\BepInEx\plugins\BudgetAirpods-InsanityRemastered"

**Comment by Senjay-id** [comment]
Closing this issue as it was resolved by the final update

**Comment by HamedAlmanthari** [comment]
![image](https://github.com/BudgetAirpods/InsanityRemastered/assets/133137232/2ea77243-dcf9-4c69-8450-ad684cb9bd02)

this is v1.1.2 but it says v1.1.1 in console. it looks like you uploaded wrong files or something to thunderstore lmao

![image](https://github.com/BudgetAirpods/InsanityRemastered/assets/133137232/160fd037-9f04-4fea-a35c-750f85a01fdc)

yes i deleted cache and reinstalled the mod.

**Comment by Noranecore** [comment]
> Closing this issue as it was resolved by the final update

No, it still isn't

**Comment by IceCreamCrape** [comment]
The error was resolved by placing the files in the plugins path.

There appears to be an error in the mod path.
Please take out the files.

![image](https://github.com/BudgetAirpods/InsanityRemastered/assets/106359587/18822ad2-b202-41aa-924b-9064459d3d22)
