### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ChooMcoo** [BudgetAirpods/InsanityRemastered#9]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SanityRewrittenMod.General.InsanityRemastered_AI.SetupVariables () (at <249334095d8147a486dcde16e6fe1abf>:0)
SanityRewrittenMod.PlayerHallucination.SetupVariables () (at <249334095d8147a486dcde16e6fe1abf>:0)
SanityRewrittenMod.General.InsanityRemastered_AI.OnEnable () (at <249334095d8147a486dcde16e6fe1abf>:0)
UnityEngine.GameObject:AddComponent()
SanityRewrittenMod.SanityMainManager:SavePlayerModel()
SanityRewrittenMod.SanityMainManager:SceneLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

If you need any additional details let me know. I'm playing with about a dozen other mods.

**Comment by BudgetAirpods** [comment]
I'm aware of this error and have fixed it (though it's not released yet). It has to due with the order of how I executed the caching of the player model. It shouldn't break the game/mod, but it's better to have no errors at all. Thank you!
